name: WSF - Lessons
markdown: redcarpet
highlighter: rouge

gems:
  - jekyll-assets

collections:
  exercices:
    output: true
  slides:
    output: true

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

defaults:
  -
    scope:
      path: ""
    values:
      layout: slide
      reveal:
        controls: true
        progress: true
        slideNumber: false
        history: false
        keyboard: true
        overview: true
        center: true
        touch: true
        loop: false
        rtl: false
        fragments: true
        embedded: false
        autoSlide: 0
        autoSlideStoppable: true
        mouseWheel: false
        hideAddressBar: true
        previewLinks: false
        transition: default
        transitionSpeed: default
        backgroundTransition: default
        viewDistance: 3
        parallaxBackgroundImage:
        parallaxBackgroundSize:
        theme: default
